services:
  gospin_dev:
    container_name: gospin_dev
    image: gospindev
    environment:
      - PORT=${PORT:-8083}
      - WAITING_SERVER_PORT=${WAITING_SERVER_PORT:-8085}
      - GO_SPIN_MISC_LOG_LEVEL=debug
      - GO_SPIN_CONFIG_PATH=/app/config
      - GID=991
    ports:
      - "${PORT:-8083}:${PORT:-8083}"
      - "${WAITING_SERVER_PORT:-8085}:${WAITING_SERVER_PORT:-8085}"
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/config
    build:
      dockerfile: dev.Dockerfile
    deploy:
     resources:
      limits:
        cpus: '2'
