services:
  gospin:
    container_name: gospin
    image: bassista/gospin:latest
    environment:
      - PORT=${PORT:-8083}
      - GO_SPIN_MISC_LOG_LEVEL=info
      - GO_SPIN_MISC_CORS_ALLOWED_ORIGINS=*
    ports:
      - "${PORT:-8083}:${PORT:-8083}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /your/path/to/config_dir:/app/config
