services:
  gospin:
    container_name: gospin
    image: gospin
    environment:
      - PORT=${PORT:-8083}
    ports:
      - "${PORT:-8083}:${PORT:-8083}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   
