services:
  gospin:
    container_name: gospin
    image: bassista/gospin:latest
    environment:
      - PORT=${PORT:-8083}
      - WAITING_SERVER_PORT=${WAITING_SERVER_PORT:-8085}
      - GO_SPIN_MISC_LOG_LEVEL=info
      - GO_SPIN_MISC_CORS_ALLOWED_ORIGINS=*
      - GO_SPIN_CONFIG_PATH=/app/config
    ports:
      - "${PORT:-8083}:${PORT:-8083}"
      - "${WAITING_SERVER_PORT:-8085}:${WAITING_SERVER_PORT:-8085}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /your/path/to/config_dir:/app/config
