server:
  port: 8080
  waiting_server_port: 8081
  shutdown_timeout_secs: 5
data:
  file_path: ./config/data/config.json
  persist_interval_secs: 5
  base_url: "http://localhost/"  # Base URL for container URL generation, supports $1 token
  refresh_interval_secs: 60       # Interval for UI auto-refresh (seconds)
  stats_refresh_interval_secs: 120  # Interval for container stats refresh (seconds)
misc:
  gin_mode: debug 
  runtime_type: docker  # possible values: memory, docker
  cors_allowed_origins: "*"   
  log_level: debug
  log_format: text  
    

